name: Run CI Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cfn-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Nodejs 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i
        working-directory: ./pca-ui/src/lambda

      - name: Run unit tests
        run: npm t
        working-directory: ./pca-ui/src/lambda
        
  publish-artifacts:
    needs: [cfn-linter, api-tests]
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Copy CloudFormation templates"
        run: |
          chmod +x publish.sh
          publish.sh 'danpcacicd'
          
